# Generated by Django 4.2.28 on 2026-02-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_add_officer_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
    ]
