# Generated by Django 6.0.2 on 2026-02-05 11:31

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_add_resolution_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolution_proof',
            field=models.FileField(blank=True, null=True, upload_to=complaints.models.resolution_proof_upload_path),
        ),
    ]
