# Generated by Django 6.0.2 on 2026-02-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("WATER_SUPPLY", "Water Supply"),
                            ("ROADS_TRANSPORT", "Roads & Transport"),
                            ("SANITATION", "Sanitation"),
                            ("ELECTRICITY", "Electricity"),
                            ("PUBLIC_HEALTH", "Public Health"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("head_of_department", models.CharField(blank=True, max_length=100)),
                ("contact_number", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("priority", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint Category",
                "verbose_name_plural": "Complaint Categories",
                "db_table": "complaint_categories",
                "ordering": ["department", "name"],
                "unique_together": {("department", "name")},
            },
        ),
    ]
