import os
import django
from django.test import Client
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mcms_config.settings')
django.setup()

from accounts.models import Citizen
from departments.models import Department, ComplaintCategory
from complaints.models import Complaint

client = Client()

results = []

# 1. Create test citizen user
username = 'testuser'
email = 'testuser@example.com'
mobile = '9999999999'
password = 'Testpass123!'

try:
    user = Citizen.objects.filter(username=username).first()
    if not user:
        user = Citizen.objects.create_user(username=username, email=email, mobile=mobile, password=password)
        user.is_verified = True
        user.save()
    results.append(('create_user', 'created' if user else 'exists'))
except Exception as e:
    results.append(('create_user', f'ERROR {e}'))

# 2. Login via test client
login_ok = client.login(username=username, password=password)
results.append(('login', login_ok))

# 3. Access dashboard
resp = client.get('/complaints/dashboard/')
results.append(('dashboard_status', resp.status_code))

# 4. Access submit page and post a complaint
resp = client.get('/complaints/submit/')
results.append(('submit_get', resp.status_code))

# Ensure a department exists
dept_code = Department.DEPARTMENT_CHOICES[0][0]
dept = Department.objects.filter(code=dept_code).first()
if not dept:
    dept = Department.objects.create(code=dept_code, name=Department.DEPARTMENT_CHOICES[0][1])

# Create a category
cat = ComplaintCategory.objects.filter(department=dept).first()
if not cat:
    cat = ComplaintCategory.objects.create(department=dept, name='General', description='General issues')

from io import BytesIO
from django.core.files.uploadedfile import SimpleUploadedFile

file_content = BytesIO(b"PDF TEST")
uploaded = SimpleUploadedFile('test.pdf', file_content.getvalue(), content_type='application/pdf')

post_data = {
    'department': dept.code,
    'category': cat.id,
    'ward_number': '12',
    'area': 'Test Area',
    'landmark': 'Near Park',
    'subject': 'E2E Test Complaint',
    'description': 'This is a test complaint generated by automated e2e script for verification.',
}

resp = client.post('/complaints/submit/', post_data, follow=True, FILES={'proof_file': uploaded})
results.append(('submit_post_status', resp.status_code))

# 5. Find complaint created
created = Complaint.objects.filter(subject='E2E Test Complaint').first()
results.append(('complaint_created', bool(created)))

# 6. Test AJAX categories endpoint
resp = client.get(f'/complaints/ajax/load-categories/?department_id={dept.code}')
results.append(('ajax_categories', resp.status_code, resp.json()))

# Print results
for r in results:
    print(r)
